# certificate resource yaml

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: try-wildcard-cert
  namespace: coder
spec:
  commonName: "*.${TUNNELD_WILDCARD_DOMAIN}"
  secretName: try-wildcard-tls
  dnsNames:
    - "wg.${TUNNELD_WILDCARD_DOMAIN}"
    - "${TUNNELD_WILDCARD_DOMAIN}"
    - "*.${TUNNELD_WILDCARD_DOMAIN}"
  issuerRef:
    name: letsencrypt-rfc2136
    kind: ClusterIssuer
    group: cert-manager.io
