apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: powerdns
  name: pdns
  namespace: powerdns
spec:
  ingressClassName: nginx
  rules:
    - host: ${PDNS_API_INGRESS}
      http:
        paths:
          - backend:
              service:
                name: auth-web
                port:
                  number: 8081
            path: /
            pathType: ImplementationSpecific
  tls:
    - secretName: "wildcard-tls"
      hosts:
        - ${PDNS_API_INGRESS}
