---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: ingress-nginx
spec:
  secretName: wildcard-tls
  dnsNames:
    - "*.${domain}"
    - "${domain}"
  issuerRef:
    # name: letsencrypt-staging
    name: letsencrypt-rfc2136
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: coder
spec:
  secretName: wildcard-tls
  dnsNames:
    - "*.${domain}"
    - "${domain}"
    - "whataboutthistime.${domain}"
  issuerRef:
    name: letsencrypt-rfc2136
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: coder-wildcard-cert
  namespace: coder
spec:
  secretName: coder-wildcard-tls
  dnsNames:
    - "*.coder.${domain}"
    - "coder.${domain}"
  issuerRef:
    name: letsencrypt-rfc2136
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: try-wildcard-cert
  namespace: coder
spec:
  secretName: try-wildcard-tls
  dnsNames:
    - "*.try.${domain}"
    - "try.${domain}"
  issuerRef:
    name: letsencrypt-rfc2136
    kind: ClusterIssuer
    group: cert-manager.io
