---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-receiver
  namespace: flux-system
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-http01"
spec:
  rules:
    - host: "flux-webhook.${domain}"
      http:
        paths:
          - backend:
              service:
                name: webhook-receiver
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - secretName: "wildcard-tls"
      hosts:
        - "flux-webhook.${domain}"
